### ISSUE TITLE
Touble in intallation

### ISSUE THREAD

**Issue by 2019C** [czimaginginstitute/AreTomo3#13]
Hi Shawn,

I am trying to compile the AreTomo3 on my workstation ubuntu 22.04.4. However, I encountered the following error message:

(base) csun@01-6411:~/AreTomo3/AreTomo3$  make exe -f makefile11 CUDAHOME=/usr/local/cuda

AreTomo/Recon/GWeightProjs.cpp has been compiled.

/usr/bin/ld: /home/csun/AreTomo3/AreTomo3/LibSrc/Lib/libmrcfile.a(CSaveMainHeader.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE

/usr/bin/ld: failed to set dynamic section sizes: bad value

collect2: error: ld returned 1 exit status

make: *** [makefile11:267: exe] Error 1

My gcc version is 11.4.0
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Do you know how to work around this issue?

Thanks in advance.
Chen

**Comment by frozenfas** [comment]
I have the same issue was this resolved?

**Comment by dzyla** [comment]
I was able to compile it by modifying the makefile11 to replace the previous code section with this part: 

```
exe: $(OBJS)
	@$(NVCC) -g -G -m64 $(OBJS) \
	$(PRJLIB)/libmrcfile.a $(PRJLIB)/libutil.a \
	-L$(CUDALIB) -L$(CUDALIB)/stubs\
	-L$(CONDA)/lib \
	-L/usr/lib64 \
	-lcufft -lcudart -lcuda -lnvToolsExt -ltiff -lc -lm -lpthread \
	-Xlinker -no-pie \
	-o AreTomo3
	@echo AreTomo3 has been generated.```

Now, AreTomo3 complies properly.

**Comment by frozenfas** [comment]
Thanks, @dzyla.  I tried your suggestion and was able to compile AreTomo3.
