### ISSUE TITLE
How to obtain newst.com and tilt.com fles for Aretomo-reconstructed tomograms for Relion integration?

### ISSUE THREAD

**Issue by abnerabner** [czimaginginstitute/AreTomo3#19]
Hi,

Thank you for providing such a helpful tool! I’ve recently reconstructed tomograms using AreTomo and have successfully picked particles to generate a `.star` file. My next step is to have a try to import these into Relion for subtomogram averaging. However, I’ve noticed that tomograms reconstructed with AreTomo lack `newst.com` and `tilt.com` files, which are typically available when using Etomo.

Could you please advise if there’s a way to obtain or generate these files when using AreTomo? Your guidance would be greatly appreciated!

Best regards,
Abner

**Comment by szhengczii** [comment]
@abnerabner Did you have "-OutImod 1" option enabled in your command line?

**Comment by abnerabner** [comment]
> @abnerabner Did you have "-OutImod 1" option enabled in your command line?

So sorry I just realized I forgot about it, thank you for your help very much!
