### ISSUE TITLE
what():  basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by wlugmayr** [czimaginginstitute/AreTomo3#4]
I used a working job from aretomo & aretomo2, replaced the exe with aretomo3 and sent it to P100 & A100 nodes. Unfortunatly the message below appears and no more further information. AreTomo3 was compiled with CUDA 12.1.1 on RHEL9.

#jobid : 79497576
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
#end: Fri Jun 21 10:06:59 AM CEST 2024

**Comment by szhengczii** [comment]
Please provide the full command line of AreTomo3 for debugging. AreTomo3 has very different command line arguments from AreTomo2. These two are not inter-exchangeable.

**Comment by wlugmayr** [comment]
Oh, I just replace my AreTomo1 & 2 script exe with aretomo3:

aretomo3 -InMrc tomo3.mrc -OutMrc tomo3_bin8_rec.mrc -OutBin 8 \\
    -AlignZ 300 -VolZ 500 -TiltCor 1 -FlipVol 1 –Kv 300 -PixSize 8.6 \\
    -AngFile AngleDose_tomo3.txt -Gpu 0 -OutImod 1

**Comment by wlugmayr** [comment]
Since I processed the AreTomo part in the Scipion Tomo Tutorial with EMPIAR-10164 TS_01 successfully I used the same files with the commandline (options from the beginning of your manual):
mkdir -p results
aretomo3 -InMdoc frames/TS_ -InSuffix .mdoc \\
    -OutDir ./results \\
    -PixSize 0.675 \\
    -McBin 1 \\
    -McPatch 5 5 -Group 1 4 \\
    -AtBin 4 -AtPatch 4 4 \\
    -Wbp 1 -OutImod 1 \\
    -Serial 90000 -Gpu 0 1 2 3

and AreTomo3 dies without a message at:
:
GPU 0 memory: 12207 MB
GPU 1 memory: 12207 MB
GPU 2 memory: 12207 MB
GPU 3 memory: 12207 MB

Directory: frames/
Prefix:    TS_
Suffix:    .mdoc
Skips:     
added: frames/TS_01.mrc.mdoc

GPU 0: Motion correct TS_01_000_0.0.mrc

**Comment by szhengczii** [comment]
It seems like you have got it running. I will close this issue.
