### ISSUE TITLE
Issue during tomogram reconstruction

### ISSUE THREAD

**Issue by RamteenS** [czimaginginstitute/AreTomo3#6]
Hi,
I try to run AreTomo3 but i get the following error during tomogram reconstruction: 
My command:
 
AreTomo3 -InMdoc ./frames/*.mdoc -OutDir test_Aretomo3 -PixSize 0.7894 -kV 300 -Cs 2.7 -Gpu 0 -AlignZ 800 -wbp -gain gain_ref.mrc -TotalDose 2.89 -VolZ 500 -McBin 4

The error': 
-InMdoc          ./frames/TS_11.mrc.mdoc
-InSuffix        
-InSkips         
-OutDir          test_Aretomo3/
-TmpFile         
-LogDir          /
-PixSize         0.79
-kV              300
-Cs              2.70
-FmDose          0.00000
-Serial          0
-Cmd             0
-Resume          0
-Gpu             0

Motion correction input parameters
----------------------------------
-FmIntFile       
-Gain            gain_ref.mrc
-Dark            
-DefectFile      
-EerSampling     1
-McPatch         0  0  0
-McIter          15
-McTol           0.10
-McBin           4.00
-Group           1  4
-FmRef           -1
-RotGain         0
-FlipGain        0
-InvGain         0
-Mag             1.00  1.00  0.00
-InFmMotion      0
-TiffOrder       1
                 0

Tomography input parameters
---------------------------
-TotalDose  2.890000
-AlignZ     800
-VolZ       500
-AtBin      1.00
-TiltAxis   0.00  1.00
-TiltCor    0.00  0.00
-ReconRange  -90.00  90.00
-AmpContrast  0.07
-ExtPhase   0.00  0.00
-FlipVol    0
-FlipInt    0
-Sart       20  5
-Wbp        0
-AtPatch    0  0
-OutXF      0
-Align      1
-CropVol    0  0
-OutImod    0
-DarkTol    0.70
-IntpCor    0
-CorrCTF    1 15

GPU 0 memory: 24249 MB

Load gain refereince from
   gain_ref.mrc
Gain reference has been loaded.

All mdoc files have been processed, waiting processing to finish.

GPU 0: Motion correct 2Dvs3D_53-11_00041_-40.0_Jul31_17.19.55.tif
------------------

TIFF file size & mode: 5760  4092  3  0
Rendered size & mode:  5760  4092  3  0
GPU 0 Allocation time: GPU (  0.26 GB)   0.00 s, CPU (  0.00 GB)   0.00 s
GPU 0 Allocation time: GPU (  0.35 GB)   0.00 s, CPU (  0.00 GB)   0.00 s
GPU 0 Allocation time: GPU (  0.07 GB)   0.00 s, CPU (  0.00 GB)   0.00 s
GPU 0 Allocation time: GPU (  0.26 GB)   0.00 s, CPU (  0.00 GB)   0.00 s
Create buffers: 0.10 seconds

Detect bad and hot pixels.
Mean & Std:     0.00     0.00
Hot pixel threshold:    10.00

CC Mean Std: 0.000e+00  0.000e+00
CC threshold: 0.000

Full frame alignment
Forward FFT of stack, please wait...
Fourier transform done.
Full-frame alignment has been started.
Iteration  1  Error:    87.620
Iteration  2  Error:    87.620
Iteration  3  Error:    87.620
Iteration  4  Error:    87.620
Iteration  5  Error:    87.620
Iteration  6  Error:    87.620
Iteration  7  Error:    87.620
Iteration  8  Error:    87.620
Iteration  9  Error:    87.620
Iteration 10  Error:    87.620
Iteration 11  Error:    87.620
Iteration 12  Error:    87.620
Iteration 13  Error:    87.620
Iteration 14  Error:    87.620
Iteration 15  Error:    87.620

Full-frame alignment shift
...... Frame (  1) shift:     0.000      0.000
...... Frame (  2) shift:     0.000      0.000
...... Frame (  3) shift:     0.000      0.000

Create aligned sum based upon full frame alignment.
Mag stretch: 1.000  -0.000

CCufft2D::DestroyPlan:62: no kernel image is available for execution on the device
	

AreTomo3: MaUtil/CSimpleFuncs.cpp:49: void McAreTomo::MaUtil::CheckCudaError(const char*): Assertion `0' failed.
Aborted (core dumped)
 
Any idea where the problem comes from ? 

Many thanks for the help 

Best,

Ramteen

**Comment by szhengczii** [comment]
The command line has some mistakes and misses some parameters.
AreTomo3 -InMdoc **./frames/*.mdoc** -OutDir test_Aretomo3 -PixSize 0.7894 -kV 300 -Cs 2.7 -Gpu 0 -AlignZ 800 -wbp -gain gain_ref.mrc **-TotalDose 2.89** -VolZ 500 -McBin 4

The simplest command line in your case should look like below:
AreTomo3 -InMdoc ./frames/ -InSuffix .mdoc -OutDir test_Aretomo3 -PixSize 0.7894 -kV 300 -Cs 2.7 -Gpu 0 -AlignZ 800 -wbp 1 -gain gain_ref.mrc -FmDose 2.89 -VolZ 800 -McBin 4 -Serial 1

The doc folder contains an user manual. Hope it can clarify a bit.

Sorry for the late response. Please report issues by email in the future. I do not check github on a regular base.

Best,
Shawn

**Comment by szhengczii** [comment]
Try again with "-Serial 2" to see if it helps.
