### ISSUE TITLE
space for questions about aretomo3

### ISSUE THREAD

**Issue by McHaillet** [czimaginginstitute/AreTomo3#7]
Hi again!

I had some questions about the implementation of the software. I can ask them here, but the GitHub issue system is not ideal for this in my opinion. Do you have a place for such discussions already? Otherwise I could recommend enabling the Discussion page for this GitHub repository. It makes the questions and answers publicly available and its handy that it is directly linked to the repository. 

Best,
Marten

**Comment by szhengczii** [comment]
Please send the questions directly to me by email. Happy to discuss with you.
