### ISSUE TITLE
can not be used when making a PIE object

### ISSUE THREAD

**Issue by khayatlab** [czimaginginstitute/AreTomo3#9]
Hi,
I'm getting the following error when trying to compile.

AreTomo/Recon/GWeightProjs.cpp has been compiled.
/usr/bin/ld: /home/rkhayat/Applications/AreTomo3/LibSrc/Lib/libmrcfile.a(CSaveMainHeader.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/rkhayat/Applications/AreTomo3/LibSrc/Lib/libmrcfile.a(CLoadImage.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/rkhayat/Applications/AreTomo3/LibSrc/Lib/libmrcfile.a(CLoadMrc.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/rkhayat/Applications/AreTomo3/LibSrc/Lib/libmrcfile.a(CSaveMrc.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/rkhayat/Applications/AreTomo3/LibSrc/Lib/libmrcfile.a(CLoadExtHeader.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/rkhayat/Applications/AreTomo3/LibSrc/Lib/libutil.a(Util_FileName.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/rkhayat/Applications/AreTomo3/LibSrc/Lib/libutil.a(Util_String.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/rkhayat/Applications/AreTomo3/LibSrc/Lib/libutil.a(Util_LinEqs.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/rkhayat/Applications/AreTomo3/LibSrc/Lib/libutil.a(Util_Powell.o): relocation R_X86_64_32 against symbol `_ZTV11Util_Powell' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/rkhayat/Applications/AreTomo3/LibSrc/Lib/libutil.a(Util_Thread.o): relocation R_X86_64_32 against symbol `_ZTV11Util_Thread' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
make: *** [makefile11:267: exe] Error 1

to compile: make exe -f  makefile11 CUDAHOME=/usr/local/cuda/ 
I'm using gcc version 9.40
GNU Make 4.2.1
Ubuntu 20.04.5 LTS

Any help is appreciated. Thanks.

Best wishes,
Reza

**Comment by mdppdm** [comment]
Hi, Reza. I had the same problem. You can see my post in the closed topics. Also, this is covered in the user manual.
Mike

**Comment by khayatlab** [comment]
Hi,
Thanks mdppdm. It solved the problem.

**Comment by szhengczii** [comment]
This issue has been resolved.
